### ISSUE TITLE
=quote(a2) not pulling values

### ISSUE THREAD

**Issue by first-name** [brymck/finansu#24]
Your routines always work great. Suddenly today with no change in spreadsheet no values being updated.

Went to your examples spreadsheet that came with install, and all values return blank (spaces) from all sources.

Windows 7 system. Excel 2007

**Comment by Section82** [comment]
The bloomberg quote system has not worked for me since i've been using FinAnSu back in April 2014. This still does not work. Today, google stopped pulling in prices. Nice -_-

**Comment by weismat** [comment]
Google stopped providing an official API years ago. So everything else is a hack and not officially supported. If you want guarantee that sth works, then you need a subscription service.
